# Generated by Django 3.2.9 on 2024-04-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendaFinanceira', '0005_saldoatual_date_modificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='nome_pagador',
        ),
        migrations.AddField(
            model_name='receita',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendaFinanceira.cliente', verbose_name='Nome do Pagador'),
        ),
    ]
