# Generated by Django 3.2.9 on 2024-04-11 18:54

import agendaFinanceira.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaFinanceira', '0007_auto_20240403_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Produto')),
                ('nm_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('status_produto', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7, verbose_name='Status do Produto')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Venda')),
                ('valor_producao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Produção')),
                ('image', models.FileField(blank=True, null=True, upload_to=agendaFinanceira.models.upload_to_produto, verbose_name='Foto do Produto')),
            ],
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='situacao',
            field=models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Pago', 'Pago')], db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='receita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_entrada',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo_recebimento',
            field=models.CharField(choices=[('RECEITA_PRODUTOS', 'Receita com Produtos'), ('RECEITA_SERVICOS', 'Receita com Serviços'), ('OUTRAS_RECEITAS', 'Outras Receitas')], db_index=True, default='OUTRAS_RECEITAS', max_length=90, verbose_name='Tipo de Recebimento'),
        ),
    ]
