# Generated by Django 3.2.9 on 2024-04-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendaFinanceira', '0009_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendaFinanceira.produto'),
        ),
    ]
