# Generated by Django 3.2.9 on 2024-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaFinanceira', '0010_receita_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='tipo_recebimento',
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
