# Generated by Django 3.2.9 on 2024-06-11 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='event_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Título'),
        ),
    ]
