# Generated by Django 3.2.9 on 2024-06-12 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0003_auto_20240611_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='todolist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para Redirecionamento'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Atividade Realizada'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='postpone_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Postergar Data'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='redirected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_todolist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_todolist', to=settings.AUTH_USER_MODEL),
        ),
    ]
